services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
      - REDIS_URL=redis://clare-me-redis:6379
      - JWT_SECRET=very_secret_key
    networks: 
      - clare-me-net
  redis:
    image: redis
    container_name: clare-me-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - clare-me-net
      

networks:
  clare-me-net: